### ISSUE TITLE
nbsp appears in legend when downloading categorical map as  *.png or *.pdf

### ISSUE THREAD

**Issue by larafaelivrin** [StataBS/indikatoren#544]
We used **npm run start-export-server** to solve this problem to export the indicator *.png for an entire indicator set. How can we solve the problem for the online highcharts?

![image](https://user-images.githubusercontent.com/23261816/33996304-18ec7e1c-e0e1-11e7-9c9c-899df887b127.png)

**Comment by jb3-2** [comment]
I don't know yet. We have other issues with the export server, too  (see https://forum.highcharts.com/highmaps-usage-f14/legend-text-at-wrong-position-in-export-t39916/), so I probably have to file a support request for this issue, too.

**Comment by larafaelivrin** [comment]
For the Richtplan-Print indicator set we used  **npm run start-export-server**  to solve this problem. Could this problem be solved in a similar way?

**Comment by jb3-2** [comment]
Solution: Use \u00a0 instead of &nbsp;

**Comment by jb3-2** [comment]
@larafaelivrin Another important thing: use `<br/>` instead of `<br>` - the svg file is not valid otherwise.

**Comment by jb3-2** [comment]
Not: Exporting: {allowHTML: true} is a fix for the still not 100% ideal png export through the hamburger menu (export.highcharts.com), but this leads to invalid svg due to <br> tags instead of <br/> tags in svg which leads to broken view in our website. This can be fixed by using htmltidy (or its npm module), let's try this to get the optimal state. 

Alternatively check if Highcharts 6 creates valid svg and update, since this is necessary for #439 anyway.

**Comment by larafaelivrin** [comment]
I replaced the &nbsp with \u00a0  and <br> with <br/> for the indicator set PDF_Karten.

**\u00a0**: unicode character "no-break space"
**&nbsp;**: html character "no-break space"

<br/>: In html the <br> tag has no end tag. Porbably svg reads <br> differntly...

**Comment by jb3-2** [comment]
Waiting for Highcharts 6, see #579

**Comment by jb3-2** [comment]
Replacing `&nbsp;` with its unicode works fine in xAxis labels (without allowing HTML and the Chrome / IE problems that are inherent with html foreignObjects in SVG) by replacing the labels at runtime, see https://github.com/StataBS/indikatoren/issues/637#issuecomment-380729216

**Comment by jb3-2** [comment]
@larafaelivrin Using \u00a0 as an alternative to `&nbsp;` spacer together with `legend.useHTML: true` works fine in the browser without exporting.allowHTML set to true. The PNG is not perfect, but I think we currently have to live with that. Mybe I'll create a Forum entry. 

![image](https://user-images.githubusercontent.com/7261044/39002970-16b09ada-43fa-11e8-8d8a-ae572a5e3d58.png)

**Comment by jb3-2** [comment]
Here's the Highcharts forum entry: https://forum.highcharts.com/highmaps-usage-f14/no-break-spaces-as-prefix-in-coloraxis-names-do-not-export-t40521/
